### ISSUE TITLE
Abandoned Queue Items are left with status "In Progress"

### ISSUE THREAD

**Issue by hbpe-aarhus** [itk-dev-rpa/OpenOrchestrator#63] opened 2024-02-01 13:20 UTC
If a Queue Item is picked up by a scheduler but is never finished, its status is left as "In Progress" indefinitely.

![image](https://github.com/itk-dev-rpa/OpenOrchestrator/assets/58694666/a959b137-ab07-4845-a8e1-84e37e9185f6)

An idea could be to mark Queue Items as "Abandoned" or similar if they have been "In Progress" for 24 or 48 hours (or any other suitable period of time).

**Comment by ghbm-itk** [comment] 2024-02-05 08:25
This is how UiPath does it, and that really annoyed me, because you don't control when a queue element is marked as abandoned and that might require more logic inside of the robots.

With some good arguments I could be convinced, but for now it's by design.

**Comment by ghbm-itk** [comment] 2024-02-28 09:31
You could have a "Meta robot" that goes through all queues daily and mark "In progress" elements as Failed. Then control is at least in your own hands. Your code snippet would work perfectly for that purpose. 

When I see a queue element as "In Progress" and I know the robot isn't running I just translate it to "Abandoned" in my head. Sounds like bad design when I say it out loud, but it works for me.

The queue framework should mark the queue element as Failed in case of an exception.
A queue element left as In Progress should only happen if the robot stops unexpectedly.

When do you see this being a problem?
Because I just see "In progress" as a synonym for "Abandoned" it doesn't really affect anything in my work.

**Comment by hbpe-aarhus** [comment] 2024-02-28 09:47
> You could have a "Meta robot" that goes through all queues daily and mark "In progress" elements as Failed.

Good idea. I had also just considered this route. It could have a very lenient timespan for setting the queue item to Failed (say, multiple days or even a week).

>When I see a queue element as "In Progress" and I know the robot isn't running I just translate it to "Abandoned" in my head. Sounds like bad design when I say it out loud, but it works for me.

Doesn't that speak for itself? ;)

Yes, strictly speaking it's bad design as the queue element is no longer "In Progress" but actually "Abandoned". Ideally the status of the queue element should reflect this accurately, but I think setting "Failed" status is acceptable.

>A queue element left as In Progress should only happen if the robot stops unexpectedly.

That happens daily in some processes in our current UiPath Production Tenant. I'm confident it will happen at least sometimes if/when we get production-level OpenOrchestrator processes running.

At any rate, since it's possible to change the status of an "In Progress" queue element to "Failed" either with a "Meta robot" or more specific logic in each automation proces, I think this issue can be closed.

**Comment by ghbm-itk** [comment] 2024-02-28 10:04
I could easily add a "Abandoned" tag that can be used for the purpose to differentate from "Failed".

**Closed by ghbm-itk** 2024-02-28 10:04 UTC
Labels: enhancement, wontfix

**Comment by hbpe-aarhus** [comment] 2024-02-28 10:09
Sounds good to me!
